### ISSUE TITLE
Minor XFCE Arrow Visual Bug

### ISSUE THREAD

**Issue by actionless** [actionless/oomox-gtk-theme#11]
_From @KUPOinyourWINDOW on November 19, 2017 16:12_

![screenshot_2017-11-19_16-10-38](https://user-images.githubusercontent.com/7698035/32992579-44b028ec-cd44-11e7-975a-4f10394f940c.png)

When you open up a music player, then go into the XFCE sound menu (which is GTK3) the arrows that appear to scroll have an ugly white highlight colour. Thanks for your time and work!

_Copied from original issue: actionless/oomox#108_

**Comment by actionless** [comment]
does it have it only on hover or always?

**Comment by KUPOinyourWINDOW** [comment]
Only on hover

**Comment by actionless** [comment]
i was trying Majaro XFCE vm recently (to make the recent xfce bugfixes) however i didn't found there that audio widget, what's the name of it's executable so i can install and run it? or mb the issue reproducing in some other places?

**Comment by KUPOinyourWINDOW** [comment]
I'm not too sure as I don't have much experience with Manjaro (only installed it once, and the install didn't last long).

It's the one that comes standard in Xubuntu, but that's all I know :(

**Comment by actionless** [comment]
but can you see the same problem with any other app may be?

**Comment by KUPOinyourWINDOW** [comment]
It's in all the GTK3 indicators with enough items to be scrollable

**Comment by nana-4** [comment]
In gtk+ `<=3.18`, it's defined in `.menuitem.button:hover`:
https://github.com/actionless/oomox-gtk-theme/blob/master/src/gtk-3.0/scss/widgets/_menu.scss#L129

In gtk+ `>=3.20`, it's defined in `menu > arrow:hover`:
https://github.com/actionless/oomox-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_menu.scss#L173

I think this can be fixed by replacing
 `mix($fg_color, $base_color, .1)` to `mix($menu_bg_color, $menu_fg_color, .1)`.

Or if you prefer normal menuitem colors, you can specify
 `$selected_bg_color` (and `$selected_fg_color` for `color`) like `<=3.18` menu buttons. :)

**Comment by actionless** [comment]
@nana-4 thanks a lot!

hope now it should be fine
